.circleci/config.yml, templateflow/api.py, templateflow/conf/__init__.py
This PR adds a check on ``TEMPLATEFLOW_USE_DATALAD`` (default unset
or false) which needs to evaluate to ``True`` in order to use
DataLad.
This fix addresses poldracklab/fmriprep#1534.
=> FIX: Require environment variable to use DataLad

.circleci/config.yml, templateflow/api.py
As per https://github.com/templateflow/python-client/pull/8#discussion_r264962583
=> FIX: ``api.get`` - robuster fetcher algorithm (allows S3 download on DL repos) and better error messages

templateflow/conf/config.json
Should probably also upgrade to pybids 0.9.2 after bids-standard/pybids#458 goes in.
=> FIX: Add extension entity for selection

.circleci/config.yml
Drops all the CI mechanisms to manage the skeleton. This means, for instance, we do not need to force another build of master before every release just to be sure the skeleton is updated.
Resolves: #38
=> MAINT: Transfer the burden of keeping skeleton updated over to the archive

MANIFEST.in, setup.cfg, setup.py, templateflow/api.py, templateflow/conf/__init__.py, templateflow/conf/_s3.py, templateflow/conf/tests/test_conf.py, templateflow/conf/tests/test_s3.py
This PR introduces `templateflow.conf.update()` to allow for the update
the TemplateFlow structure pointed by TEMPLATEFLOW_HOME.
It has a "local" operation mode (which uses the skeleton distributed
within the installed package) to ensure the continuity of previous work
on this line. This means that, when re-installing templateflow, the
TEMPLATEFLOW_HOME will still be updated the same way it used to be.
This PR is limited, as it does not allow to point templateflow to a
particular release of the archive. The main reason for that is that we
would need to have a version controlled repository of skeletons (which
does not exist yet).
Resolves: #37
=> ENH: Update the internal index of TemplateFlow

setup.cfg, templateflow/conf/__init__.py
this is due to the change in behavior of 0.12.x series of DataLad.
See https://github.com/datalad/datalad/issues/3759
for more info
Closes #47 
Disclaimer: I have not tried the fix anyhow
=> BF: provide path to the dataset as "dataset" argument

.github/workflows/pythonpackage.yml, .travis.yml, setup.py, templateflow/__init__.py, templateflow/conf/__init__.py, templateflow/conf/_s3.py
=> ENH: Run an automatic skeleton update on import by default

.circleci/config.yml, setup.cfg, templateflow/conf/__init__.py, templateflow/conf/_s3.py, templateflow/tests/test_api.py, templateflow/tests/test_conf.py
Closes #58 
~~Needs a unittest.~~
Also fixes the failing unittest, and catches a bug where `allow_redirect` was not being passed onto certain requests.
=> FIX: Ensure templateflow Layout is re-indexed when updating

templateflow/api.py
Adds an option to raise an error when `templateflow.get` returns an empty list.
=> ENH: Add option to raise exception on empty ``get`` query

templateflow/api.py
When downloading files, the progress display shows file sizes on the order of kilobytes, even though the requested file should be multiple megabytes in size. When I first encountered this, I thought the files may be corrupt, but this is not the case.
```
Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_desc-brain_T1w.nii.gz
3.39kB [00:00, 3.46kB/s]
```
Steps to reproduce this
```
import os
from tempfile import mkdtemp
os.environ["TEMPLATEFLOW_HOME"] = mkdtemp()
from templateflow import api
api.get("MNI152NLin2009cAsym", resolution=1, desc="brain", suffix="T1w")
```
Looking at the code, I discovered that the progress bar module `tqdm` is configured to display one download block as one byte, even though one download block can be up to …
=> [FIX] Make download progress bar display correct units

.github/workflows/pythonpackage.yml
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> FIX: Remove GH Action set-env

templateflow/api.py, templateflow/conf/__init__.py, templateflow/conf/tests/test_conf.py
We had to dismiss the ``ImportError`` to allow the update/dowonload of the TemplateFlow home skeleton at installation time, which made our unit test pass - but created this problem down the line.
Resolves: #71.
=> FIX: layout is ``None`` when PyBIDS not correctly installed

templateflow/tests/test_api.py
now that the crossref bug (https://gitlab.com/crossref/issues/-/issues/1540) is fixed.
=> REVERT: Expected bibtex entries

.github/workflows/pythonpackage.yml, templateflow/api.py, templateflow/tests/test_api.py
=> FIX: Normalize extensions for leading dot & update doctests to new resources

templateflow/api.py
Usage:
```Python
>>> from templateflow import api
>>> api.ls("MouseIn", suffix="mask")
[PosixPath('/data/templateflow/tpl-MouseIn/tpl-MouseIn_res-1_desc-brain_mask.nii.gz'), PosixPath('/data/templateflow/tpl-MouseIn/tpl-MouseIn_res-1_desc-CSF_mask.nii.gz')]
```
As opposed to ``get()`` which will actually pull these files down.
Resolves: #90.
=> ENH: Add an ``api.ls()`` function to list (without getting) files

templateflow/api.py, templateflow/tests/test_api.py
This patch allows users to access the automated querying of the layout with the ``get_*`` magic (and ``ls_*``, for TF), e.g.:
```Python
>>> from templateflow import api
>>> api.ls_atlases(template="MNI152NLin6Asym")
['DiFuMo', 'Schaefer2018', 'HOCPA', 'HCP', 'HOCPAL', 'HOSPA']
```
The existing ``get_*`` methods are not overshadowed:
```Python
>>> api.get_citations(template="MNI152NLin6Asym")
['https://doi.org/10.1016/j.neuroimage.2012.01.024',
'https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Atlases']
```
The original ``get_*`` queries are accepted:
```Python
>>> api.get_atlases()
['AAL',
'DiFuMo',
'v3',
'CerebrA',
'D99',
'WHS',
'VALiDATe',
'v4',
'Schaefer2018',
'HOCPA',
'HCP',
'CerebA',
'CCFv3',
'CHARM',
'HOCPAL',
'SARM',
'HOSPA']
```
I'm hesitant about whether we should disallow ``get_*`` (as …
=> ENH: Allow access to PyBIDS' magic ``get_*``

templateflow/api.py, templateflow/tests/test_api.py
=> ENH: Make sure existing ``layout.get_*`` are not bubbled in

.circleci/config.yml, .github/workflows/pythonpackage.yml, requirements.txt, setup.cfg, templateflow/__init__.py, templateflow/_loader.py, templateflow/conf/__init__.py, templateflow/conf/_s3.py, templateflow/conf/bids.py, templateflow/tests/test_version.py
From niworkflows tests, it looks like setuptools has finally killed off pkg_resources. Need to get a templateflow release without it.
=> MNT: Python 3.12 support, drop Python 3.7 and pkg_resources

templateflow/api.py
Replace backslashes with forward slashes in all paths. This should create correct https urls from broken windows paths, and should not affect paths from other systems.
=> FIX: Use Path.as_posix() and f-strinigs to build correct URLs on Windows

.zenodo.json, CHANGES.rst
Looking through the git log we had some uncredited contributors:
* @wiheto 
* @HippocampusGirl 
* @mfschmidt 
Please verify that I got your Zenodo entries correct. Or let me know if you prefer not to be credited.
=> REL: 23.1.0

templateflow/conf/config.json
Necessary after converting the annots of fsaverage (see templateflow/tpl-fsaverage#5).
=> ENH: Add `seg-<label>` and `scale-<number>` entities

.circleci/config.yml, .github/workflows/pythonpackage.yml
Resolves: #126.
Seems like ``pkginfo`` requires to be >1.9 so that ``twine check`` does not fail.
=> MAINT: Revise failing Pypi deployment and ``twine check``

.circleci/config.yml, pyproject.toml, templateflow/conf/tests/test_conf.py
Fixes the problem with recent datalad versions (#129).
=> MAINT: Update datalad pinned version

templateflow/__init__.py, templateflow/cli.py, templateflow/conf/__init__.py, templateflow/conf/_s3.py, templateflow/tests/test_multiproc.py
Closes #62 
This shifts skeleton extraction to a per-file basis to catch cases where directories were being created across multiple threads/procs. Additionally, this sets the groundwork for verifying individual file checksums down the line.
Python 3.13 already addressed this - https://github.com/python/cpython/commit/5d2794a16bc1639e6053300c08a78d60526aadf2
=> FIX: Avoid directory clobber during zip extraction

templateflow/cli.py, templateflow/tests/test_cli.py
Currently:
```
❯ uvx templateflow get MNI152NLin6Asym --res 2 --desc LR -s T1w
Traceback (most recent call last):
File "/home/chris/.cache/uv/archive-v0/N20Na8Y61YObB3kT5W_Jk/bin/templateflow", line 10, in <module>
sys.exit(main())
~~~~^^
File "/home/chris/.cache/uv/archive-v0/N20Na8Y61YObB3kT5W_Jk/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
~~~~~~~~~^^^^^^^^^^^^^^^^^
File "/home/chris/.cache/uv/archive-v0/N20Na8Y61YObB3kT5W_Jk/lib/python3.13/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/home/chris/.cache/uv/archive-v0/N20Na8Y61YObB3kT5W_Jk/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
File …
```
=> fix(cli): Fix crash in templateflow get when matching one file
